/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_test_1;

import Control.ValidarLogin;
import Entidad.Usuario;
import gui_test_1.Login;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Image;
import static java.awt.Label.CENTER;
import java.awt.Toolkit;
import java.beans.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

public class Admin_ListaMantenimientos extends javax.swing.JFrame {

    public String texto;
    public String user;
    public String matenimientoFecha ;

    public Admin_ListaMantenimientos(String texto, String user, String mantenimientoFecha ) {
        initComponents();
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/silunimage.png")).getImage());
        this.texto = texto;
        this.user = user;
        this.matenimientoFecha = mantenimientoFecha;
        jlFecha.setText(mantenimientoFecha);
        jlTexto.setFont(new Font("Ancizar Sans",Font.ITALIC,16));
        jlTexto.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        jlTexto.setText(texto);
        scroller.setWheelScrollingEnabled(true);
       //JScrollPane scroller = new JScrollPane(jlTexto,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        
       // this.getContentPane().add(scroller,BorderLayout.CENTER);
    }

    private Admin_ListaMantenimientos() {

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scroller = new java.awt.ScrollPane();
        jlTexto = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 77, 87));
        jPanel1.setForeground(new java.awt.Color(246, 203, 38));
        jPanel1.setMaximumSize(new java.awt.Dimension(450, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTexto.setBackground(new java.awt.Color(246, 203, 38));
        jlTexto.setForeground(new java.awt.Color(246, 203, 38));
        jlTexto.setOpaque(true);
        scroller.add(jlTexto);

        jPanel1.add(scroller, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 169, 330, 370));

        jlFecha.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jlFecha.setForeground(new java.awt.Color(255, 255, 255));
        jlFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlFecha.setText("jLabel1");
        jlFecha.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 350, -1));

        btAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_test_1/Images/boton login.png"))); // NOI18N
        btAceptar.setBorder(null);
        btAceptar.setContentAreaFilled(false);
        btAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAceptar.setPreferredSize(new java.awt.Dimension(50, 50));
        btAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_test_1/Images/boton login push.png"))); // NOI18N
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pestañitamantenimiento.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
      
this.dispose();
    }//GEN-LAST:event_btAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ListaMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ListaMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ListaMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ListaMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ListaMantenimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlTexto;
    private java.awt.ScrollPane scroller;
    // End of variables declaration//GEN-END:variables
}
